service: pos-tech-employees-ms

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  region: sa-east-1
  runtime: dotnet6
  profile: DevSandbox
  role: arn:aws:iam::985539770222:role/PosTechRole
  tracing:
    apiGateway: true
    lambda: true
  environment:
    EMPLOYEES_TABLE: PosTech-Employees
    JWT_SECRET: ${ssm:/aws/reference/secretsmanager/JwtSecret}

package:
  individually: true

functions:
  LoginFunction:
    handler: Employees::Employees.Function::FunctionHandler
    package:
      artifact: ./function.zip
    events:
      - http:
          path: /employees/login
          method: post

  CreateFunction:
    handler: Employees::Employees.Function::FunctionHandler
    package:
      artifact: ./function.zip
    events:
      - http:
          path: /employees/create
          method: post
